// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Specializedappoint is the predicate function for specializedappoint builders.
type Specializedappoint func(*sql.Selector)

// Specializeddiag is the predicate function for specializeddiag builders.
type Specializeddiag func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
