// Code generated by entc, DO NOT EDIT.

package specializeddiag

const (
	// Label holds the string label denoting the specializeddiag type in the database.
	Label = "specializeddiag"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSpecializeddiacnostictype holds the string denoting the specializeddiacnostictype field in the database.
	FieldSpecializeddiacnostictype = "specializeddiacnostictype"

	// EdgeAppointment holds the string denoting the appointment edge name in mutations.
	EdgeAppointment = "appointment"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"

	// Table holds the table name of the specializeddiag in the database.
	Table = "specializeddiags"
	// AppointmentTable is the table the holds the appointment relation/edge.
	AppointmentTable = "specializedappoints"
	// AppointmentInverseTable is the table name for the Specializedappoint entity.
	// It exists in this package in order to avoid circular dependency with the "specializedappoint" package.
	AppointmentInverseTable = "specializedappoints"
	// AppointmentColumn is the table column denoting the appointment relation/edge.
	AppointmentColumn = "diacnosticID"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "specializeddiags"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "specialistname"
)

// Columns holds all SQL columns for specializeddiag fields.
var Columns = []string{
	FieldID,
	FieldSpecializeddiacnostictype,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Specializeddiag type.
var ForeignKeys = []string{
	"specialistname",
}

var (
	// SpecializeddiacnostictypeValidator is a validator for the "specializeddiacnostictype" field. It is called by the builders before save.
	SpecializeddiacnostictypeValidator func(string) error
)
