// Code generated by entc, DO NOT EDIT.

package specializeddiag

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/jxxshark/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Specializeddiacnostictype applies equality check predicate on the "specializeddiacnostictype" field. It's identical to SpecializeddiacnostictypeEQ.
func Specializeddiacnostictype(v string) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSpecializeddiacnostictype), v))
	})
}

// SpecializeddiacnostictypeEQ applies the EQ predicate on the "specializeddiacnostictype" field.
func SpecializeddiacnostictypeEQ(v string) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSpecializeddiacnostictype), v))
	})
}

// SpecializeddiacnostictypeNEQ applies the NEQ predicate on the "specializeddiacnostictype" field.
func SpecializeddiacnostictypeNEQ(v string) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSpecializeddiacnostictype), v))
	})
}

// SpecializeddiacnostictypeIn applies the In predicate on the "specializeddiacnostictype" field.
func SpecializeddiacnostictypeIn(vs ...string) predicate.Specializeddiag {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Specializeddiag(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSpecializeddiacnostictype), v...))
	})
}

// SpecializeddiacnostictypeNotIn applies the NotIn predicate on the "specializeddiacnostictype" field.
func SpecializeddiacnostictypeNotIn(vs ...string) predicate.Specializeddiag {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Specializeddiag(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSpecializeddiacnostictype), v...))
	})
}

// SpecializeddiacnostictypeGT applies the GT predicate on the "specializeddiacnostictype" field.
func SpecializeddiacnostictypeGT(v string) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSpecializeddiacnostictype), v))
	})
}

// SpecializeddiacnostictypeGTE applies the GTE predicate on the "specializeddiacnostictype" field.
func SpecializeddiacnostictypeGTE(v string) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSpecializeddiacnostictype), v))
	})
}

// SpecializeddiacnostictypeLT applies the LT predicate on the "specializeddiacnostictype" field.
func SpecializeddiacnostictypeLT(v string) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSpecializeddiacnostictype), v))
	})
}

// SpecializeddiacnostictypeLTE applies the LTE predicate on the "specializeddiacnostictype" field.
func SpecializeddiacnostictypeLTE(v string) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSpecializeddiacnostictype), v))
	})
}

// SpecializeddiacnostictypeContains applies the Contains predicate on the "specializeddiacnostictype" field.
func SpecializeddiacnostictypeContains(v string) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSpecializeddiacnostictype), v))
	})
}

// SpecializeddiacnostictypeHasPrefix applies the HasPrefix predicate on the "specializeddiacnostictype" field.
func SpecializeddiacnostictypeHasPrefix(v string) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSpecializeddiacnostictype), v))
	})
}

// SpecializeddiacnostictypeHasSuffix applies the HasSuffix predicate on the "specializeddiacnostictype" field.
func SpecializeddiacnostictypeHasSuffix(v string) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSpecializeddiacnostictype), v))
	})
}

// SpecializeddiacnostictypeEqualFold applies the EqualFold predicate on the "specializeddiacnostictype" field.
func SpecializeddiacnostictypeEqualFold(v string) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSpecializeddiacnostictype), v))
	})
}

// SpecializeddiacnostictypeContainsFold applies the ContainsFold predicate on the "specializeddiacnostictype" field.
func SpecializeddiacnostictypeContainsFold(v string) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSpecializeddiacnostictype), v))
	})
}

// HasAppointment applies the HasEdge predicate on the "appointment" edge.
func HasAppointment() predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AppointmentTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AppointmentTable, AppointmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAppointmentWith applies the HasEdge predicate on the "appointment" edge with a given conditions (other predicates).
func HasAppointmentWith(preds ...predicate.Specializedappoint) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AppointmentInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AppointmentTable, AppointmentColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(UserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Specializeddiag) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Specializeddiag) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Specializeddiag) predicate.Specializeddiag {
	return predicate.Specializeddiag(func(s *sql.Selector) {
		p(s.Not())
	})
}
