// Code generated by entc, DO NOT EDIT.

package patient

const (
	// Label holds the string label denoting the patient type in the database.
	Label = "patient"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAge holds the string denoting the age field in the database.
	FieldAge = "age"

	// EdgeAppointment holds the string denoting the appointment edge name in mutations.
	EdgeAppointment = "appointment"

	// Table holds the table name of the patient in the database.
	Table = "patients"
	// AppointmentTable is the table the holds the appointment relation/edge.
	AppointmentTable = "specializedappoints"
	// AppointmentInverseTable is the table name for the Specializedappoint entity.
	// It exists in this package in order to avoid circular dependency with the "specializedappoint" package.
	AppointmentInverseTable = "specializedappoints"
	// AppointmentColumn is the table column denoting the appointment relation/edge.
	AppointmentColumn = "patientid"
)

// Columns holds all SQL columns for patient fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldAge,
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)
