// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"github.com/jxxshark/app/ent/migrate"

	"github.com/jxxshark/app/ent/patient"
	"github.com/jxxshark/app/ent/specializedappoint"
	"github.com/jxxshark/app/ent/specializeddiag"
	"github.com/jxxshark/app/ent/user"

	"github.com/facebookincubator/ent/dialect"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Patient is the client for interacting with the Patient builders.
	Patient *PatientClient
	// Specializedappoint is the client for interacting with the Specializedappoint builders.
	Specializedappoint *SpecializedappointClient
	// Specializeddiag is the client for interacting with the Specializeddiag builders.
	Specializeddiag *SpecializeddiagClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Patient = NewPatientClient(c.config)
	c.Specializedappoint = NewSpecializedappointClient(c.config)
	c.Specializeddiag = NewSpecializeddiagClient(c.config)
	c.User = NewUserClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: tx, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		Patient:            NewPatientClient(cfg),
		Specializedappoint: NewSpecializedappointClient(cfg),
		Specializeddiag:    NewSpecializeddiagClient(cfg),
		User:               NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(*sql.Driver).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %v", err)
	}
	cfg := config{driver: &txDriver{tx: tx, drv: c.driver}, log: c.log, debug: c.debug, hooks: c.hooks}
	return &Tx{
		config:             cfg,
		Patient:            NewPatientClient(cfg),
		Specializedappoint: NewSpecializedappointClient(cfg),
		Specializeddiag:    NewSpecializeddiagClient(cfg),
		User:               NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Patient.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := config{driver: dialect.Debug(c.driver, c.log), log: c.log, debug: true, hooks: c.hooks}
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Patient.Use(hooks...)
	c.Specializedappoint.Use(hooks...)
	c.Specializeddiag.Use(hooks...)
	c.User.Use(hooks...)
}

// PatientClient is a client for the Patient schema.
type PatientClient struct {
	config
}

// NewPatientClient returns a client for the Patient from the given config.
func NewPatientClient(c config) *PatientClient {
	return &PatientClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `patient.Hooks(f(g(h())))`.
func (c *PatientClient) Use(hooks ...Hook) {
	c.hooks.Patient = append(c.hooks.Patient, hooks...)
}

// Create returns a create builder for Patient.
func (c *PatientClient) Create() *PatientCreate {
	mutation := newPatientMutation(c.config, OpCreate)
	return &PatientCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Patient.
func (c *PatientClient) Update() *PatientUpdate {
	mutation := newPatientMutation(c.config, OpUpdate)
	return &PatientUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PatientClient) UpdateOne(pa *Patient) *PatientUpdateOne {
	mutation := newPatientMutation(c.config, OpUpdateOne, withPatient(pa))
	return &PatientUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PatientClient) UpdateOneID(id int) *PatientUpdateOne {
	mutation := newPatientMutation(c.config, OpUpdateOne, withPatientID(id))
	return &PatientUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Patient.
func (c *PatientClient) Delete() *PatientDelete {
	mutation := newPatientMutation(c.config, OpDelete)
	return &PatientDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *PatientClient) DeleteOne(pa *Patient) *PatientDeleteOne {
	return c.DeleteOneID(pa.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *PatientClient) DeleteOneID(id int) *PatientDeleteOne {
	builder := c.Delete().Where(patient.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PatientDeleteOne{builder}
}

// Create returns a query builder for Patient.
func (c *PatientClient) Query() *PatientQuery {
	return &PatientQuery{config: c.config}
}

// Get returns a Patient entity by its id.
func (c *PatientClient) Get(ctx context.Context, id int) (*Patient, error) {
	return c.Query().Where(patient.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PatientClient) GetX(ctx context.Context, id int) *Patient {
	pa, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return pa
}

// QueryAppointment queries the appointment edge of a Patient.
func (c *PatientClient) QueryAppointment(pa *Patient) *SpecializedappointQuery {
	query := &SpecializedappointQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := pa.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(patient.Table, patient.FieldID, id),
			sqlgraph.To(specializedappoint.Table, specializedappoint.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, patient.AppointmentTable, patient.AppointmentColumn),
		)
		fromV = sqlgraph.Neighbors(pa.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *PatientClient) Hooks() []Hook {
	return c.hooks.Patient
}

// SpecializedappointClient is a client for the Specializedappoint schema.
type SpecializedappointClient struct {
	config
}

// NewSpecializedappointClient returns a client for the Specializedappoint from the given config.
func NewSpecializedappointClient(c config) *SpecializedappointClient {
	return &SpecializedappointClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `specializedappoint.Hooks(f(g(h())))`.
func (c *SpecializedappointClient) Use(hooks ...Hook) {
	c.hooks.Specializedappoint = append(c.hooks.Specializedappoint, hooks...)
}

// Create returns a create builder for Specializedappoint.
func (c *SpecializedappointClient) Create() *SpecializedappointCreate {
	mutation := newSpecializedappointMutation(c.config, OpCreate)
	return &SpecializedappointCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Specializedappoint.
func (c *SpecializedappointClient) Update() *SpecializedappointUpdate {
	mutation := newSpecializedappointMutation(c.config, OpUpdate)
	return &SpecializedappointUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SpecializedappointClient) UpdateOne(s *Specializedappoint) *SpecializedappointUpdateOne {
	mutation := newSpecializedappointMutation(c.config, OpUpdateOne, withSpecializedappoint(s))
	return &SpecializedappointUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SpecializedappointClient) UpdateOneID(id int) *SpecializedappointUpdateOne {
	mutation := newSpecializedappointMutation(c.config, OpUpdateOne, withSpecializedappointID(id))
	return &SpecializedappointUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Specializedappoint.
func (c *SpecializedappointClient) Delete() *SpecializedappointDelete {
	mutation := newSpecializedappointMutation(c.config, OpDelete)
	return &SpecializedappointDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *SpecializedappointClient) DeleteOne(s *Specializedappoint) *SpecializedappointDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *SpecializedappointClient) DeleteOneID(id int) *SpecializedappointDeleteOne {
	builder := c.Delete().Where(specializedappoint.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SpecializedappointDeleteOne{builder}
}

// Create returns a query builder for Specializedappoint.
func (c *SpecializedappointClient) Query() *SpecializedappointQuery {
	return &SpecializedappointQuery{config: c.config}
}

// Get returns a Specializedappoint entity by its id.
func (c *SpecializedappointClient) Get(ctx context.Context, id int) (*Specializedappoint, error) {
	return c.Query().Where(specializedappoint.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SpecializedappointClient) GetX(ctx context.Context, id int) *Specializedappoint {
	s, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return s
}

// QueryUser queries the user edge of a Specializedappoint.
func (c *SpecializedappointClient) QueryUser(s *Specializedappoint) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(specializedappoint.Table, specializedappoint.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, specializedappoint.UserTable, specializedappoint.UserColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryPatient queries the patient edge of a Specializedappoint.
func (c *SpecializedappointClient) QueryPatient(s *Specializedappoint) *PatientQuery {
	query := &PatientQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(specializedappoint.Table, specializedappoint.FieldID, id),
			sqlgraph.To(patient.Table, patient.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, specializedappoint.PatientTable, specializedappoint.PatientColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySpecializeddiag queries the specializeddiag edge of a Specializedappoint.
func (c *SpecializedappointClient) QuerySpecializeddiag(s *Specializedappoint) *SpecializeddiagQuery {
	query := &SpecializeddiagQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(specializedappoint.Table, specializedappoint.FieldID, id),
			sqlgraph.To(specializeddiag.Table, specializeddiag.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, specializedappoint.SpecializeddiagTable, specializedappoint.SpecializeddiagColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SpecializedappointClient) Hooks() []Hook {
	return c.hooks.Specializedappoint
}

// SpecializeddiagClient is a client for the Specializeddiag schema.
type SpecializeddiagClient struct {
	config
}

// NewSpecializeddiagClient returns a client for the Specializeddiag from the given config.
func NewSpecializeddiagClient(c config) *SpecializeddiagClient {
	return &SpecializeddiagClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `specializeddiag.Hooks(f(g(h())))`.
func (c *SpecializeddiagClient) Use(hooks ...Hook) {
	c.hooks.Specializeddiag = append(c.hooks.Specializeddiag, hooks...)
}

// Create returns a create builder for Specializeddiag.
func (c *SpecializeddiagClient) Create() *SpecializeddiagCreate {
	mutation := newSpecializeddiagMutation(c.config, OpCreate)
	return &SpecializeddiagCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for Specializeddiag.
func (c *SpecializeddiagClient) Update() *SpecializeddiagUpdate {
	mutation := newSpecializeddiagMutation(c.config, OpUpdate)
	return &SpecializeddiagUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SpecializeddiagClient) UpdateOne(s *Specializeddiag) *SpecializeddiagUpdateOne {
	mutation := newSpecializeddiagMutation(c.config, OpUpdateOne, withSpecializeddiag(s))
	return &SpecializeddiagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SpecializeddiagClient) UpdateOneID(id int) *SpecializeddiagUpdateOne {
	mutation := newSpecializeddiagMutation(c.config, OpUpdateOne, withSpecializeddiagID(id))
	return &SpecializeddiagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Specializeddiag.
func (c *SpecializeddiagClient) Delete() *SpecializeddiagDelete {
	mutation := newSpecializeddiagMutation(c.config, OpDelete)
	return &SpecializeddiagDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *SpecializeddiagClient) DeleteOne(s *Specializeddiag) *SpecializeddiagDeleteOne {
	return c.DeleteOneID(s.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *SpecializeddiagClient) DeleteOneID(id int) *SpecializeddiagDeleteOne {
	builder := c.Delete().Where(specializeddiag.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SpecializeddiagDeleteOne{builder}
}

// Create returns a query builder for Specializeddiag.
func (c *SpecializeddiagClient) Query() *SpecializeddiagQuery {
	return &SpecializeddiagQuery{config: c.config}
}

// Get returns a Specializeddiag entity by its id.
func (c *SpecializeddiagClient) Get(ctx context.Context, id int) (*Specializeddiag, error) {
	return c.Query().Where(specializeddiag.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SpecializeddiagClient) GetX(ctx context.Context, id int) *Specializeddiag {
	s, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return s
}

// QueryAppointment queries the appointment edge of a Specializeddiag.
func (c *SpecializeddiagClient) QueryAppointment(s *Specializeddiag) *SpecializedappointQuery {
	query := &SpecializedappointQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(specializeddiag.Table, specializeddiag.FieldID, id),
			sqlgraph.To(specializedappoint.Table, specializedappoint.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, specializeddiag.AppointmentTable, specializeddiag.AppointmentColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUser queries the user edge of a Specializeddiag.
func (c *SpecializeddiagClient) QueryUser(s *Specializeddiag) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := s.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(specializeddiag.Table, specializeddiag.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, specializeddiag.UserTable, specializeddiag.UserColumn),
		)
		fromV = sqlgraph.Neighbors(s.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SpecializeddiagClient) Hooks() []Hook {
	return c.hooks.Specializeddiag
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Create returns a create builder for User.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Create returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{config: c.config}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	u, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return u
}

// QueryAppointment queries the appointment edge of a User.
func (c *UserClient) QueryAppointment(u *User) *SpecializedappointQuery {
	query := &SpecializedappointQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(specializedappoint.Table, specializedappoint.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, user.AppointmentTable, user.AppointmentColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QuerySpecializeddiag queries the specializeddiag edge of a User.
func (c *UserClient) QuerySpecializeddiag(u *User) *SpecializeddiagQuery {
	query := &SpecializeddiagQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(specializeddiag.Table, specializeddiag.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, user.SpecializeddiagTable, user.SpecializeddiagColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}
