// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/jxxshark/app/ent/predicate"
	"github.com/jxxshark/app/ent/specializedappoint"
	"github.com/jxxshark/app/ent/specializeddiag"
	"github.com/jxxshark/app/ent/user"
)

// SpecializeddiagUpdate is the builder for updating Specializeddiag entities.
type SpecializeddiagUpdate struct {
	config
	hooks      []Hook
	mutation   *SpecializeddiagMutation
	predicates []predicate.Specializeddiag
}

// Where adds a new predicate for the builder.
func (su *SpecializeddiagUpdate) Where(ps ...predicate.Specializeddiag) *SpecializeddiagUpdate {
	su.predicates = append(su.predicates, ps...)
	return su
}

// SetSpecializeddiacnostictype sets the specializeddiacnostictype field.
func (su *SpecializeddiagUpdate) SetSpecializeddiacnostictype(s string) *SpecializeddiagUpdate {
	su.mutation.SetSpecializeddiacnostictype(s)
	return su
}

// AddAppointmentIDs adds the appointment edge to Specializedappoint by ids.
func (su *SpecializeddiagUpdate) AddAppointmentIDs(ids ...int) *SpecializeddiagUpdate {
	su.mutation.AddAppointmentIDs(ids...)
	return su
}

// AddAppointment adds the appointment edges to Specializedappoint.
func (su *SpecializeddiagUpdate) AddAppointment(s ...*Specializedappoint) *SpecializeddiagUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddAppointmentIDs(ids...)
}

// SetUserID sets the user edge to User by id.
func (su *SpecializeddiagUpdate) SetUserID(id int) *SpecializeddiagUpdate {
	su.mutation.SetUserID(id)
	return su
}

// SetNillableUserID sets the user edge to User by id if the given value is not nil.
func (su *SpecializeddiagUpdate) SetNillableUserID(id *int) *SpecializeddiagUpdate {
	if id != nil {
		su = su.SetUserID(*id)
	}
	return su
}

// SetUser sets the user edge to User.
func (su *SpecializeddiagUpdate) SetUser(u *User) *SpecializeddiagUpdate {
	return su.SetUserID(u.ID)
}

// Mutation returns the SpecializeddiagMutation object of the builder.
func (su *SpecializeddiagUpdate) Mutation() *SpecializeddiagMutation {
	return su.mutation
}

// RemoveAppointmentIDs removes the appointment edge to Specializedappoint by ids.
func (su *SpecializeddiagUpdate) RemoveAppointmentIDs(ids ...int) *SpecializeddiagUpdate {
	su.mutation.RemoveAppointmentIDs(ids...)
	return su
}

// RemoveAppointment removes appointment edges to Specializedappoint.
func (su *SpecializeddiagUpdate) RemoveAppointment(s ...*Specializedappoint) *SpecializeddiagUpdate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveAppointmentIDs(ids...)
}

// ClearUser clears the user edge to User.
func (su *SpecializeddiagUpdate) ClearUser() *SpecializeddiagUpdate {
	su.mutation.ClearUser()
	return su
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (su *SpecializeddiagUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := su.mutation.Specializeddiacnostictype(); ok {
		if err := specializeddiag.SpecializeddiacnostictypeValidator(v); err != nil {
			return 0, &ValidationError{Name: "specializeddiacnostictype", err: fmt.Errorf("ent: validator failed for field \"specializeddiacnostictype\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SpecializeddiagMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *SpecializeddiagUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SpecializeddiagUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SpecializeddiagUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SpecializeddiagUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   specializeddiag.Table,
			Columns: specializeddiag.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: specializeddiag.FieldID,
			},
		},
	}
	if ps := su.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Specializeddiacnostictype(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: specializeddiag.FieldSpecializeddiacnostictype,
		})
	}
	if nodes := su.mutation.RemovedAppointmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specializeddiag.AppointmentTable,
			Columns: []string{specializeddiag.AppointmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: specializedappoint.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.AppointmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specializeddiag.AppointmentTable,
			Columns: []string{specializeddiag.AppointmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: specializedappoint.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   specializeddiag.UserTable,
			Columns: []string{specializeddiag.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   specializeddiag.UserTable,
			Columns: []string{specializeddiag.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{specializeddiag.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// SpecializeddiagUpdateOne is the builder for updating a single Specializeddiag entity.
type SpecializeddiagUpdateOne struct {
	config
	hooks    []Hook
	mutation *SpecializeddiagMutation
}

// SetSpecializeddiacnostictype sets the specializeddiacnostictype field.
func (suo *SpecializeddiagUpdateOne) SetSpecializeddiacnostictype(s string) *SpecializeddiagUpdateOne {
	suo.mutation.SetSpecializeddiacnostictype(s)
	return suo
}

// AddAppointmentIDs adds the appointment edge to Specializedappoint by ids.
func (suo *SpecializeddiagUpdateOne) AddAppointmentIDs(ids ...int) *SpecializeddiagUpdateOne {
	suo.mutation.AddAppointmentIDs(ids...)
	return suo
}

// AddAppointment adds the appointment edges to Specializedappoint.
func (suo *SpecializeddiagUpdateOne) AddAppointment(s ...*Specializedappoint) *SpecializeddiagUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddAppointmentIDs(ids...)
}

// SetUserID sets the user edge to User by id.
func (suo *SpecializeddiagUpdateOne) SetUserID(id int) *SpecializeddiagUpdateOne {
	suo.mutation.SetUserID(id)
	return suo
}

// SetNillableUserID sets the user edge to User by id if the given value is not nil.
func (suo *SpecializeddiagUpdateOne) SetNillableUserID(id *int) *SpecializeddiagUpdateOne {
	if id != nil {
		suo = suo.SetUserID(*id)
	}
	return suo
}

// SetUser sets the user edge to User.
func (suo *SpecializeddiagUpdateOne) SetUser(u *User) *SpecializeddiagUpdateOne {
	return suo.SetUserID(u.ID)
}

// Mutation returns the SpecializeddiagMutation object of the builder.
func (suo *SpecializeddiagUpdateOne) Mutation() *SpecializeddiagMutation {
	return suo.mutation
}

// RemoveAppointmentIDs removes the appointment edge to Specializedappoint by ids.
func (suo *SpecializeddiagUpdateOne) RemoveAppointmentIDs(ids ...int) *SpecializeddiagUpdateOne {
	suo.mutation.RemoveAppointmentIDs(ids...)
	return suo
}

// RemoveAppointment removes appointment edges to Specializedappoint.
func (suo *SpecializeddiagUpdateOne) RemoveAppointment(s ...*Specializedappoint) *SpecializeddiagUpdateOne {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveAppointmentIDs(ids...)
}

// ClearUser clears the user edge to User.
func (suo *SpecializeddiagUpdateOne) ClearUser() *SpecializeddiagUpdateOne {
	suo.mutation.ClearUser()
	return suo
}

// Save executes the query and returns the updated entity.
func (suo *SpecializeddiagUpdateOne) Save(ctx context.Context) (*Specializeddiag, error) {
	if v, ok := suo.mutation.Specializeddiacnostictype(); ok {
		if err := specializeddiag.SpecializeddiacnostictypeValidator(v); err != nil {
			return nil, &ValidationError{Name: "specializeddiacnostictype", err: fmt.Errorf("ent: validator failed for field \"specializeddiacnostictype\": %w", err)}
		}
	}

	var (
		err  error
		node *Specializeddiag
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SpecializeddiagMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SpecializeddiagUpdateOne) SaveX(ctx context.Context) *Specializeddiag {
	s, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return s
}

// Exec executes the query on the entity.
func (suo *SpecializeddiagUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SpecializeddiagUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SpecializeddiagUpdateOne) sqlSave(ctx context.Context) (s *Specializeddiag, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   specializeddiag.Table,
			Columns: specializeddiag.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: specializeddiag.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Specializeddiag.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := suo.mutation.Specializeddiacnostictype(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: specializeddiag.FieldSpecializeddiacnostictype,
		})
	}
	if nodes := suo.mutation.RemovedAppointmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specializeddiag.AppointmentTable,
			Columns: []string{specializeddiag.AppointmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: specializedappoint.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.AppointmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   specializeddiag.AppointmentTable,
			Columns: []string{specializeddiag.AppointmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: specializedappoint.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   specializeddiag.UserTable,
			Columns: []string{specializeddiag.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   specializeddiag.UserTable,
			Columns: []string{specializeddiag.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	s = &Specializeddiag{config: suo.config}
	_spec.Assign = s.assignValues
	_spec.ScanValues = s.scanValues()
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{specializeddiag.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return s, nil
}
