/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntPatient,
    EntPatientFromJSON,
    EntPatientFromJSONTyped,
    EntPatientToJSON,
    EntSpecializeddiag,
    EntSpecializeddiagFromJSON,
    EntSpecializeddiagFromJSONTyped,
    EntSpecializeddiagToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntSpecializedappointEdges
 */
export interface EntSpecializedappointEdges {
    /**
     * 
     * @type {EntPatient}
     * @memberof EntSpecializedappointEdges
     */
    patient?: EntPatient;
    /**
     * 
     * @type {EntSpecializeddiag}
     * @memberof EntSpecializedappointEdges
     */
    specializeddiag?: EntSpecializeddiag;
    /**
     * 
     * @type {EntUser}
     * @memberof EntSpecializedappointEdges
     */
    user?: EntUser;
}

export function EntSpecializedappointEdgesFromJSON(json: any): EntSpecializedappointEdges {
    return EntSpecializedappointEdgesFromJSONTyped(json, false);
}

export function EntSpecializedappointEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntSpecializedappointEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patient': !exists(json, 'Patient') ? undefined : EntPatientFromJSON(json['Patient']),
        'specializeddiag': !exists(json, 'Specializeddiag') ? undefined : EntSpecializeddiagFromJSON(json['Specializeddiag']),
        'user': !exists(json, 'User') ? undefined : EntUserFromJSON(json['User']),
    };
}

export function EntSpecializedappointEdgesToJSON(value?: EntSpecializedappointEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patient': EntPatientToJSON(value.patient),
        'specializeddiag': EntSpecializeddiagToJSON(value.specializeddiag),
        'user': EntUserToJSON(value.user),
    };
}


