/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntSpecializeddiagEdges,
    EntSpecializeddiagEdgesFromJSON,
    EntSpecializeddiagEdgesFromJSONTyped,
    EntSpecializeddiagEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntSpecializeddiag
 */
export interface EntSpecializeddiag {
    /**
     * 
     * @type {EntSpecializeddiagEdges}
     * @memberof EntSpecializeddiag
     */
    edges?: EntSpecializeddiagEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntSpecializeddiag
     */
    id?: number;
    /**
     * Specializeddiacnostictype holds the value of the "specializeddiacnostictype" field.
     * @type {string}
     * @memberof EntSpecializeddiag
     */
    specializeddiacnostictype?: string;
}

export function EntSpecializeddiagFromJSON(json: any): EntSpecializeddiag {
    return EntSpecializeddiagFromJSONTyped(json, false);
}

export function EntSpecializeddiagFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntSpecializeddiag {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntSpecializeddiagEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'specializeddiacnostictype': !exists(json, 'specializeddiacnostictype') ? undefined : json['specializeddiacnostictype'],
    };
}

export function EntSpecializeddiagToJSON(value?: EntSpecializeddiag | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntSpecializeddiagEdgesToJSON(value.edges),
        'id': value.id,
        'specializeddiacnostictype': value.specializeddiacnostictype,
    };
}


