export * from './ControllersSpecializedappoint';
export * from './EntPatient';
export * from './EntPatientEdges';
export * from './EntSpecializedappoint';
export * from './EntSpecializedappointEdges';
export * from './EntSpecializeddiag';
export * from './EntSpecializeddiagEdges';
export * from './EntUser';
export * from './EntUserEdges';
